### ISSUE TITLE
Documentation for Mac

### ISSUE THREAD

**Issue by bruxy70** [kounoike/obs-virtualbg#69]
Can you please update the documentation with the installation instructions for Mac? I am not sure where to copy the two directories.
Will this work on Mac M1 chips?
Thanks!

**Comment by kounoike** [comment]
Mac build artifacts is not useful for everyone. Because it's not signed.
If you want to run obs-virtualbg on mac, you should build it by yourself (build on M1 chips is OK).
However, I do not want to provide support on how to build it. (I provide only one Hint: GitHub workflows)

or, support for me ($99/yr) refs: #70 

If you write well-written build steps document, document PR is also welcome!

**Comment by bruxy70** [comment]
Thanks. I think I got the artifacts (e/g/ hete https://github.com/kounoike/obs-virtualbg/actions/runs/2007633415)
There are two dirs *- bin and data, but I have no idea where to copy them in OBS. 
I go to Applications-OBS-Contents. Tried to put them in Plugins or Resources-data. Did not show up.
